version: '2'

networks:
    bibbox-default-network:
      external: true

services:
  §§INSTANCE-youtrack:
    image: jetbrains/youtrack:2018.4.48406 
    container_name:  §§INSTANCE-youtrack
    restart: unless-stopped
    networks:
      - bibbox-default-network
    ports:
      - "§§PORT:80"
    depends_on:
      - §§INSTANCE-youtrack-data
    volumes_from: 
      - §§INSTANCE-youtrack-data

  §§INSTANCE-youtrack-data:
    image: busybox
    container_name: §§INSTANCE-youtrack-data
    volumes:
      - ./mounted/data:/opt/youtrack/data
      - ./mounted/backup:/opt/youtrack/backup

